"""Generate FSRS-6 test vectors from the reference implementation.

Ground rule 3 forbids third-party dependencies in GraphCore, so FSRS is ported
rather than imported; this script is how the port is held honest. It was run
BEFORE the Swift port existed, so the port could not be tuned to its own bugs.

Oracle: open-spaced-repetition/py-fsrs @ 8add2d3.

    git clone https://github.com/open-spaced-repetition/py-fsrs
    cd py-fsrs && git checkout 8add2d3 && pip install typing_extensions
    python3 /path/to/Scripts/gen-fsrs-vectors.py \\
        /path/to/Tests/GraphCoreTests/Fixtures/fsrs-vectors.json

Bumping the oracle means regenerating the fixture AND updating
`FSRSVersion.oracle` — `fixtureMatchesThePortedParameters` fails if they drift.

Learning/relearning steps are emptied so `review_card` reduces to pure memory
updates — the Knowledge Tree ports the memory model, not Anki's step machine.
"""

import json
import random
import subprocess
import sys
from datetime import datetime, timedelta, timezone

sys.path.insert(0, ".")
from fsrs import Card, Rating, Scheduler  # noqa: E402
from fsrs.scheduler import DEFAULT_PARAMETERS  # noqa: E402

RATINGS = [Rating.Again, Rating.Hard, Rating.Good, Rating.Easy]
commit = subprocess.check_output(["git", "rev-parse", "HEAD"]).decode().strip()

memory_only = Scheduler(enable_fuzzing=False, learning_steps=(), relearning_steps=())

out = {
    "source": "open-spaced-repetition/py-fsrs",
    "commit": commit,
    "algorithm": "FSRS-6",
    "parameters": list(DEFAULT_PARAMETERS),
    "note": (
        "Generated by scratchpad/gen_vectors.py against the reference "
        "implementation. Memory-model vectors only: learning_steps and "
        "relearning_steps are empty, so review_card performs no step "
        "scheduling. Elapsed days are whole days, matching py-fsrs's "
        "(t2-t1).days truncation."
    ),
}

# --- Per-function grids -----------------------------------------------------

out["initialStability"] = [
    {"rating": int(r), "stability": memory_only._initial_stability(rating=r)}
    for r in RATINGS
]
out["initialDifficulty"] = [
    {"rating": int(r), "difficulty": memory_only._initial_difficulty(rating=r, clamp=True)}
    for r in RATINGS
]

out["retrievability"] = [
    {"stability": s, "elapsedDays": d, "retrievability": (1 + memory_only._FACTOR * d / s) ** memory_only._DECAY}
    for s in (0.1, 1.0, 2.5, 10.0, 53.62691, 365.0)
    for d in (0, 1, 3, 10, 100, 1000)
]

out["nextDifficulty"] = [
    {"difficulty": d, "rating": int(r), "next": memory_only._next_difficulty(difficulty=d, rating=r)}
    for d in (1.0, 2.5, 5.0, 6.3574867, 8.0, 10.0)
    for r in RATINGS
]

out["shortTermStability"] = [
    {"stability": s, "rating": int(r), "next": memory_only._short_term_stability(stability=s, rating=r)}
    for s in (0.001, 0.1, 1.0, 2.5, 10.0, 100.0)
    for r in RATINGS
]

out["nextStability"] = [
    {
        "difficulty": d,
        "stability": s,
        "retrievability": rr,
        "rating": int(r),
        "next": memory_only._next_stability(difficulty=d, stability=s, retrievability=rr, rating=r),
    }
    for d in (1.0, 5.0, 6.3574867, 10.0)
    for s in (0.1, 1.0, 10.0, 53.62691, 365.0)
    for rr in (0.05, 0.5, 0.9, 0.99)
    for r in RATINGS
]

out["nextInterval"] = [
    {"stability": s, "desiredRetention": 0.9, "days": memory_only._next_interval(stability=s)}
    for s in (0.001, 0.5, 1.0, 2.5, 10.0, 53.62691, 365.0, 100000.0)
]

# --- End-to-end review sequences -------------------------------------------

def run_sequence(steps):
    """steps: [(rating, days_since_previous_review)] -> per-step memory state."""
    scheduler = Scheduler(enable_fuzzing=False, learning_steps=(), relearning_steps=())
    card = Card()
    when = datetime(2022, 11, 29, 12, 30, 0, 0, timezone.utc)
    trace = []
    for rating, gap in steps:
        when += timedelta(days=gap)
        retrievability_before = scheduler.get_card_retrievability(card, current_datetime=when)
        card, _ = scheduler.review_card(card=card, rating=rating, review_datetime=when)
        trace.append(
            {
                "rating": int(rating),
                "elapsedDays": gap,
                "retrievabilityBefore": retrievability_before,
                "stability": card.stability,
                "difficulty": card.difficulty,
            }
        )
    return trace


sequences = []

# The two published vectors from py-fsrs's own test suite.
sequences.append(
    {
        "name": "test_memo_state (py-fsrs tests/test_basic.py)",
        "steps": [(Rating.Again, 0), (Rating.Good, 0), (Rating.Good, 1),
                  (Rating.Good, 3), (Rating.Good, 8), (Rating.Good, 21)],
        "expectFinalStability": 53.62691,
        "expectFinalDifficulty": 6.3574867,
    }
)
sequences.append(
    {
        "name": "repeated Easy reviews drive difficulty to the floor",
        "steps": [(Rating.Easy, 0)] * 10,
        "expectFinalDifficulty": 1.0,
    }
)

rng = random.Random(20260807)
for i in range(40):
    length = rng.randint(1, 12)
    steps = [
        (rng.choice(RATINGS), rng.choice([0, 0, 1, 2, 3, 7, 14, 30, 180, 365]))
        for _ in range(length)
    ]
    sequences.append({"name": f"random-{i:02d}", "steps": steps})

for sequence in sequences:
    sequence["trace"] = run_sequence(sequence["steps"])
    sequence["steps"] = [{"rating": int(r), "elapsedDays": g} for r, g in sequence["steps"]]

out["sequences"] = sequences

path = sys.argv[1]
with open(path, "w") as handle:
    json.dump(out, handle, indent=2, sort_keys=True)
    handle.write("\n")

counts = {k: len(v) for k, v in out.items() if isinstance(v, list) and k != "parameters"}
print(f"wrote {path}")
print("vector counts:", counts)
print("total sequence steps:", sum(len(s["trace"]) for s in sequences))
